services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URI=postgres://postgres:senha@postgres:5432/forms_activities_db?sslmode=disable
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12102021
      POSTGRES_DB: forms_activities_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
